import std/[os, streams, strutils, tables]

proc getDataDir*(): string =
  let base = getEnv("XDG_DATA_HOME", getEnv("HOME") / ".local/share")
  let dir = base / "hindi-ime"
  createDir(dir)
  return dir

proc getRimeDir*(): string =
  let base = getEnv("XDG_DATA_HOME", getEnv("HOME") / ".local/share")
  let dir = getEnv("HINDI_IME_RIME_DIR", base / "fcitx5/rime")
  createDir(dir)
  return dir

proc getHwnbBin*(): string =
  let dataPath = getDataDir() / "wordnet_hindi_dict.bin"
  if fileExists(dataPath): dataPath
  else: currentSourcePath.parentDir / "wordnet_hindi_dict.bin"

proc getRimeDictOut*(): string =
  getRimeDir() / "hindi_ai.dict.yaml"

type
  WordEntry = object
    phonetic: string
    hindi: string

proc normalizeToHinglish*(word: string): seq[string] =
  let raw = word.strip()
  if raw.len == 0: return @[]

  var r = raw
  # Long vowels
  r = r.replace("ā", "a").replace("Ā", "A")
  r = r.replace("ī", "i").replace("Ī", "I")
  r = r.replace("ū", "u").replace("Ū", "U")
  # Sibilants
  r = r.replace("ś", "sh").replace("Ś", "Sh")
  r = r.replace("ṣ", "sh").replace("Ṣ", "Sh")
  # Nasals
  r = r.replace("ñ", "n").replace("ṅ", "ng")
  r = r.replace("ṇ", "n").replace("ṃ", "n").replace("ṁ", "n")
  # Retroflex
  r = r.replace("ṭ", "t").replace("ḍ", "d")
  # Misc
  r = r.replace("ḥ", "h").replace("ṛ", "ri").replace("ṝ", "ri")
  r = r.replace("ḷ", "li").replace("ḹ", "li")
  r = r.toLowerAscii()

  var variants = @[r]

  # Cluster transforms
  if "jñ" in raw or "jn" in r:
    variants.add(r.replace("jn", "gy"))
  if "kṣ" in raw:
    variants.add(r.replace("ks", "ksh"))
    variants.add(r.replace("ks", "x"))
  if "sh" in r:
    variants.add(r.replace("sh", "s"))

  # Schwa deletion at end
  var schwaVariants: seq[string] = @[]
  for v in variants:
    if v.len > 3 and v[^1] == 'a':
      if not (raw.endsWith("ā") or raw.endsWith("Ā") or v.endsWith("aa") or v.endsWith("ya")):
        schwaVariants.add(v[0 ..< v.len - 1])
  variants.add(schwaVariants)

  # Deduplicate
  result = @[]
  for v in variants:
    let clean = v.strip().toLowerAscii()
    if clean.len > 0 and clean notin result:
      result.add(clean)

proc loadHWNB(binPath: string): seq[WordEntry] =
  result = @[]
  if not fileExists(binPath):
    echo "❌ Binary HWNB file not found: ", binPath
    return

  var fs = newFileStream(binPath, fmRead)
  if fs == nil: return

  var magic = fs.readStr(4)
  if magic != "HWNB":
    echo "❌ Invalid HWNB Header: ", magic
    fs.close()
    return

  var entryCount = fs.readInt32()
  echo "⚡ Reading HWNB Pure Binary Format... Total Keys: ", entryCount

  for i in 0 ..< entryCount:
    if fs.atEnd(): break
    let keyLen = fs.readUint16().int
    let pkey = fs.readStr(keyLen)
    let candCount = fs.readUint16().int
    for c in 0 ..< candCount:
      let candLen = fs.readUint16().int
      let hword = fs.readStr(candLen)
      result.add(WordEntry(phonetic: pkey, hindi: hword))

  fs.close()

proc generateRimeDict() =
  let binPath = getHwnbBin()
  let entries = loadHWNB(binPath)
  echo "🚀 Building Rime Dictionary from Pure Nim HWNB Stream..."

  let rimeOut = getRimeDictOut()
  var f = open(rimeOut, fmWrite)
  f.writeLine("# Rime dictionary: hindi_ai")
  f.writeLine("# Generated by Pure Nim HWNB Binary Engine (Zero Python / Zero JSON)")
  f.writeLine("---")
  f.writeLine("name: hindi_ai")
  f.writeLine("version: \"1.0\"")
  f.writeLine("sort: by_weight")
  f.writeLine("use_preset_vocabulary: false")
  f.writeLine("...")
  f.writeLine("")

  var seen = initTable[string, bool]()
  var count = 0
  for item in entries:
    let hword = item.hindi.strip()
    if hword.len == 0: continue
    let variants = normalizeToHinglish(item.phonetic)
    for pkey in variants:
      let hashKey = pkey & ":" & hword
      if not seen.hasKey(hashKey):
        f.writeLine(hword & "\t" & pkey)
        seen[hashKey] = true
        inc count

  f.close()
  echo "✅ Success! Pure Nim Binary HWNB parsed ", count, " entries into ", rimeOut

when isMainModule:
  generateRimeDict()
